'use client'
import './globals.css'
import axios from 'axios';
import { AuthContextProvider } from './component/AuthContext';

// export const metadata = {
//   title: '소모임',
//   description: 'Generated by JS, EJ',
// }


export default function RootLayout({ children }) {

  axios.defaults.baseURL = process.env.NEXT_PUBLIC_SERVER_BASE_URL + "/api";

  return (
    <html lang="ko">
    <title>소모임</title>
    <AuthContextProvider>
      <body>{children}</body>
    </AuthContextProvider>
    </html>
  )
}
