import './globals.css'
import axios from 'axios';

export const metadata = {
  title: '소모임',
  description: 'Generated by JS, EJ',
}


export default function RootLayout({ children }) {

  axios.defaults.baseURL = process.env.local.NEXT_PUBLIC_SERVER_BASE_URL + "/api";

  return (
    <html lang="ko">
      <body>{children}</body>
    </html>
  )
}
