import './globals.css'

export const metadata = {
  title: '소모임',
  description: 'Generated by JS, EJ',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>{children}</body>
    </html>
  )
}
